### ISSUE TITLE
transaction.commit_unless_managed() missing

### ISSUE THREAD

**Issue by eedeep** [stefanfoulis/django-graceful-session-cleanup#6]
It seems that a call to `transaction.commit_unless_managed()` is missing after the `cursor.execute()` call. Without this, for me, running Mysql with InnoDB as the database engine, nothing actually ends up getting deleted (even though the log output from graceful session cleanup reports that rows are being deleted). 

Does this sound right? It seems like something obvious that would have been noticed by now.

**Comment by stefanfoulis** [comment]
Looks reasonable. Does this still work with myisam tables?

**Comment by eedeep** [comment]
I just converted my django_session table to MyISAM and ran graceful session cleanup with the pull request code in place and it deletes expired session rows with a problem, so yeah looks to be fine.

**Comment by stefanfoulis** [comment]
Awesome, thanks for testing.
