### ISSUE TITLE
Doesn't support PostgreSQL (or mention supported DBs)

### ISSUE THREAD

**Issue by omad** [stefanfoulis/django-graceful-session-cleanup#8]
PostgreSQL doesn't support LIMIT on a DELETE FROM statement, so this management command fails.

At a minimum the README should mention that django-graceful-session-cleanup is currently only for MySQL.

**Comment by stefanfoulis** [comment]
Do you happen to know a similar sql statement that works in postgres?

**Comment by omad** [comment]
There's not a drop in equivalent, unfortunately. I found that running a raw "DELETE FROM django_session WHERE expire_date < now()" ran fast enough for the million odd rows I'd accumulated.

It was mostly the no mention of DB support that I found off-putting.

**Comment by stefanfoulis** [comment]
since there is no drop-in replacement, I've added a warning in the readme for now.

**Comment by stefanfoulis** [comment]
A possible way to add postgres support and still delete the sessions in chunks:
fetch a bunch of PKs with a `SELECT LIMIT` and then delete them directly by PK.

**Comment by stefanfoulis** [comment]
Maybe something like this:

``` sql
DELETE FROM django_session 
WHERE id = any (array(SELECT id FROM django_session WHERE expire_date<now() LIMIT 10));
```

(from http://stackoverflow.com/questions/5170546/how-do-i-delete-a-fixed-number-of-rows-with-sorting-in-postgresql/5170996#5170996)

**Comment by omad** [comment]
The `django_session` table doesn't have an `id` column. The follow works, but I'll have to test it at work tomorrow against a big table to know whether it's actually any faster than just deleting in one go.

```
DELETE FROM django_session 
WHERE session_key = any (array(SELECT session_key FROM django_session WHERE expire_date<now() LIMIT 10));
```

I believe PostgreSQL has much finer grained locking, so deleting from a large table isn't a big blocking problem like with MySQL.

**Comment by stefanfoulis** [comment]
right. we might even be making things worse for postgres.
